name: otapp_bus_seat_map
description: A flexible bus seat map widget for Flutter. Designed for bus booking apps using Otapp Services API.
version: 0.1.4
homepage: https://github.com/benardmseti/otapp_bus_seat_map
repository: https://github.com/benardmseti/otapp_bus_seat_map
issue_tracker: https://github.com/benardmseti/otapp_bus_seat_map/issues

topics:
  - widget
  - seat-map
  - booking
  - ui
  - bus-booking

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
